version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22 # Or 20, match your Lambda runtime
    commands:
      - npm install -g aws-sam-cli # Install SAM CLI
  pre_build:
    commands:
      - echo "Installing Lambda function dependencies..."
      - cd src && npm install 
      - echo "Dependencies installed in src directory."
  build:
    commands:
      - echo "Building and packaging the SAM application..."
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name TranslatorBackendStack --s3-bucket translatorbucketkh --region us-east-1 --capabilities CAPABILITY_IAM
artifacts:
  files:
    - '**/*' # Not strictly needed if sam deploy handles everything, but good practice